server:
  port: 8084

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: job-microservice
          uri: http://localhost:8080
          predicates:
            - Path=/jobs/**
        - id: company-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/companies/**
        - id: aggregator-service
          uri: http://localhost:8082
          predicates:
            - Path=/company/**
